[workspace]

members = [
  "moonramp-core",
  "moonramp-encryption",
  "moonramp-entity",
  "moonramp-http",
  "moonramp-migration",
  "moonramp-registry",
  "moonramp-rpc",
  "moonramp-wallet",
]

exclude = [
]
