[package]
name = "moonramp-program-test-sale"
version = "0.1.20"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lunar = { version = "^0.1", path = "../lunar" }

[profile.dev]
lto = true
opt-level = 's'

[profile.release]
lto = true
opt-level = 'z'
