version: 2.1
jobs:
  test-unit:
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run:
          name: "Unit Test"
          command: "cargo test"
  build-release:
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run:
          name: "Build Release"
          command: "cargo build --release"
  build-docker-image:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Build Docker Image"
          command: "docker build . -t moonramp/moonramp:$CIRCLE_SHA1"
      - run:
          name: "Get Version"
          command: "echo 'export MOONRAMP_VERSION=$(docker run moonramp/moonramp:$CIRCLE_SHA1 --version | cut -d\" \" -f2)' >> $BASH_ENV"
      - run:
          name: "Tag Docker Image"
          command: "docker tag moonramp/moonramp:$CIRCLE_SHA1 moonramp/moonramp:$MOONRAMP_VERSION"
      - run:
          name: "Push Docker Image"
          command: |
              docker login -u moonramp -p $DOCKER_HUB_ACCESS_TOKEN
              docker push moonramp/moonramp:$CIRCLE_SHA1
              docker push moonramp/moonramp:$MOONRAMP_VERSION
workflows:
  test-workflow:
    jobs:
      - test-unit
  build-release-workflow:
    jobs:
      - build-release
  build-docker-image-workflow:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build-docker-image:
          context:
            - dockerhub
