version: 2.1
executors:
  build-executor:
    docker:
      - image: cimg/rust:1.62.0
    working_directory: /tmp/moonramp
  github-release-executor:
    docker:
      - image: cimg/go:1.18.4
    working_directory: /tmp/moonramp
jobs:
  test-unit:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: "Unit Test"
          command: "cargo test"
  build-dev:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: "Build Development"
          command: "cargo build"
  build-release:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: "Build Release"
          command: "cargo build --release"
      - persist_to_workspace:
          root: target
          paths:
            - release/moonramp-migration
  github-release:
    executor: github-release-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./bin
      - run:
          name: "Github Release"
          command: |
            go install github.com/tcnksm/ghr@latest
            ghr -t ${GITHUB_ACCESS_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./bin
  docker-release:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Build Docker Image"
          command: "docker build . -t moonramp/moonramp:$CIRCLE_WORKFLOW_JOB_ID"
      - run:
          name: "Tag Docker Image"
          command: |
            docker tag moonramp/moonramp:$CIRCLE_WORKFLOW_JOB_ID moonramp/moonramp:$CIRCLE_SHA1
            docker tag moonramp/moonramp:$CIRCLE_WORKFLOW_JOB_ID moonramp/moonramp:$CIRCLE_TAG
      - run:
          name: "Push Docker Image"
          command: |
              docker login -u moonramp -p $DOCKER_HUB_ACCESS_TOKEN
              docker push moonramp/moonramp:$CIRCLE_SHA1
              docker push moonramp/moonramp:$MOONRAMP_VERSION
workflows:
  test-workflow:
    jobs:
      - test-unit
  build-dev-workflow:
    jobs:
      - build-dev
  github-release-workflow:
    jobs:
      - build-release:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - github-release:
          requires:
            - build-release
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          context:
            - github
  docker-release-workflow:
    jobs:
      - docker-release:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          context:
            - dockerhub
