[package]
name = "lunar-macro"
version = "0.1.16"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
quote = "1.0"
syn = { version = "1.0.91", features = ["full"] }
