[package]
name = "moonramp-entity"
version = "0.1.4"
edition = "2021"

[lib]
name = "moonramp_entity"
path = "src/lib.rs"

[features]
testing = []

[dependencies]
moonramp-core = { version = "^0.1", path = "../moonramp-core", features = ["lib", "sql"] }
