version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
  bitcoin:
    image: moonramp/bitcoin:0.1.3-v23
    command: "-chain=regtest"
    ports:
    - "18443:18443"
