name: Docker Image CI
on:
  pull_request:
    branches:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  moonramp-dev:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'
    steps:
    - uses: actions/checkout@v3
    - name: Build Moonramp Docker Image
      run: |
        docker build . --build-arg artifact_mode='' --build-arg artifact_path='debug' --tag moonramp/moonramp:${GITHUB_RUN_ID}
  moonramp-release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    env:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Build Moonramp Docker Image
      run: |
        docker build . --tag moonramp/moonramp:${GITHUB_RUN_ID}
    - name: Tag Moonramp Docker Image
      run: |
        docker tag moonramp/moonramp:${GITHUB_RUN_ID} moonramp/moonramp:$GITHUB_SHA
        docker tag moonramp/moonramp:${GITHUB_RUN_ID} moonramp/moonramp:$GITHUB_REF_NAME
    - name: Push Moonramp Docker Image
      run: |
        docker login -u moonramp -p $DOCKER_HUB_ACCESS_TOKEN
        docker push moonramp/moonramp:$GITHUB_SHA
        docker push moonramp/moonramp:$GITHUB_REF_NAME
