name: Docs CI
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
env:
  CARGO_TERM_COLOR: "always"
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install mdBook
      run: cargo install mdbook
    - name: Build Docs
      run: |
        cd guide
        mdbook build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: MoonRamp/moonramp.github.io
        publish_branch: master
        publish_dir: ./book
