name: Docs CI
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
env:
  CARGO_TERM_COLOR: "always"
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install mdBook
      run: cargo install mdbook
    - name: Setup out folder
      run: |
        mkdir out
    - name: Build Book
      run: |
        mdbook build book -d out
    - name: Build Docs
      run: |
        cargo doc --target-dir out
        rm -rf out/debug
    - uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.MOONRAMP_GITHUB_IO_DEPLOY_KEY }}
        external_repository: MoonRamp/moonramp.github.io
        publish_branch: master
        publish_dir: ./out
